name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Run progrAM
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo blah
        
